### ISSUE TITLE
Hi! The project is really nice. I have issue on how to prepare the Denoising_DIV2K?

### ISSUE THREAD

**Issue by yingqichao** [FanChiMao/SUNet#2]
I opened https://data.vision.ee.ethz.ch/cvl/DIV2K/ and found that there is no matching result with "Denoising". Thanks!

**Comment by FanChiMao** [comment]
Thanks for your interest.

For synthesized image denoising, we usually use the high-resolution dataset (e.g. DIV2K) as training data.
Then, cropping the HR images to suitable size and adding certain (non-blind) or uncertain (blind) gaussian noise level to generate the training set.

In our experiments, we use [DIV2K_noise.m](https://github.com/FanChiMao/SUNet/blob/main/datasets/DIV2K_noise.m) and [DIV2K_noise_val.m](https://github.com/FanChiMao/SUNet/blob/main/datasets/DIV2K_noise_val.m) to manually generate the pair gaussian noise training data.

**Comment by yingqichao** [comment]
I just find your PaperSummary is also very nice! It seems you are also an expert on JavaScript. An additional question: is there anty platform that you could recommend to me (a newbie to JS but willing to learn) to write some similar reading notes online? Thanks!

**Comment by FanChiMao** [comment]
Pff, I learned JavaScript because of the graduation topic of the university and self-study from scratch. 
I don't think I am good at JS at all 😂.
I learned the JS by continuously fixing the bugs and searched the solutions from online or books. 
In summary, my ability of JavaScript is not solid, I think you should asking others expert of JS. 
Thank you for your affirmation 😎
