### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by zhengweilu** [FanChiMao/SUNet#4]
i search the dataset to find it,but it only have image file . where are noisey images? can you tell me?

**Comment by FanChiMao** [comment]
For image denoising, especially the synthesized noise like gaussian, pepper with salt and speckle noise.
We usually generated noisy images by yourself, because it is quite convenient to adding certain type of noises.
In our experiments, we followed the same experimental setups of image denoising ([RDUNet](https://ieeexplore.ieee.org/document/9360532), [DHDN](https://ieeexplore.ieee.org/document/9025693) and [DIDN](https://ieeexplore.ieee.org/document/9025411)) which using the DIV2K as training data.
You can use [DIV2K_noise.m](https://github.com/FanChiMao/SUNet/blob/main/datasets/DIV2K_noise.m) and [DIV2K_noise_val.m](https://github.com/FanChiMao/SUNet/blob/main/datasets/DIV2K_noise_val.m) to manually generate the pair gaussian noise training data.
More details about training set can be found in [SUNet](https://arxiv.org/abs/2202.14009), experiment section, part B.
