### ISSUE TITLE
There is no network_parameters

### ISSUE THREAD

**Issue by zhangbaijin** [FanChiMao/SUNet#8]
Thanks for your contibution, and is there any lost?
` from utils import network_parameters`

**Comment by FanChiMao** [comment]
Because `utils` is a python module (`__init__.py`), we can directly import all of them.

It's same as `from utils.model_utils import network_parameters`

The class `network_parameters` can be found in 

https://github.com/FanChiMao/SUNet/blob/e4f38eb7cd0dd5bfe20a5c861696768baff837b3/utils/model_utils.py#L63-L65
