### ISSUE TITLE
'Demo_any_resolution.py' Artefacts

### ISSUE THREAD

**Issue by MrBled** [FanChiMao/SUNet#9]
Hi! Thanks for making your implementation of SWIN block denoising available! 

I am experimenting with denoising with 512x512 images, however using the demo_any_resolution.py code, I've found that there are some noticeable artefacts at block borders. Is there a way to improve this? I used the smallest stride I could but blocking artefacts were still visible. 

Alternatively, could we train a version of SUNet for 512x512 resolution?

**Comment by FanChiMao** [comment]
Hello! 

Because the positional encoding fix the image size after training process ([SwinIR issue](https://github.com/JingyunLiang/SwinIR/issues/9)), the matrix size of queue, key and value also restricted in testing. Most of solutions are using sliding window approach to demo on different testing images, but causing the obvious boundary effect. 

In fact, original transformer is first proposed to high-level vision task (e.g. classification) which resizing the testing images to fixed resolution (e.g. 224, 256...). However, image denoising belongs to pixel-wise vision task, we can't casually resize the input image. In other word, the slide window method is necessary and boundary effect is unavoidable for traditional transformer when testing image size different from training image. (SwinIR, Restormer solve this problem, but I still study their methods😅)

If you want to test on 512x512 image without any  artifact, the fundamental solution is train a version of SUNet for 512x512 as you saying But it still happen artifact when testing others image size😥.
